### PR TITLE
refactor: restructure source layout

### PR DESCRIPTION
**Pull request by hferentschik**
- moving scripts into subdirectry
- introducing BUILD_DIR var to make build and clean target consistent
- moving code into cmd resp internal

fixes issue #55

### CODE REVIEW

**Comment by jglick** [comment]
> moving scripts into subdirectory

IIUC all of `scripts/jacoco_*.sh` are slated to be deleted.

`updatebot.sh` must be at top level I think.

**Comment by hferentschik** [comment]
> IIUC all of scripts/jacoco_*.sh are slated to be deleted.

Right,  I seem to recall the same thing. I will remove them

> updatebot.sh must be at top level I think.

I see it is called in the Jenkinsfile. I can I can update the path there, right?

**Comment by hferentschik** [comment]
> updatebot.sh must be at top level I think.

@jglick on that note, I am wondering about the second line in this script. There is no ` jenkins-x-extensions-repository.yaml`

```bash
updatebot push-regex -r "\s+tag: (.*)" -v v$(cat VERSION) --previous-line "\s+-?\s+remote: ${GIT_PROVIDER}/${GITHUB_ORG}/${APP_NAME}" jenkins-x-extensions-repository.yaml
```

**Comment by hferentschik** [comment]
@jglick I pushed an update

**Review by deanesmith — APPROVED** [review]

**Comment by jglick** [comment]
> There is no ` jenkins-x-extensions-repository.yaml`

I believe this is another leftover from the world of pre-app extensions, and lives here: https://github.com/jenkins-x/jenkins-x-extensions/blob/master/jenkins-x-extensions-repository.yaml

**Pull request merged**
