### PR TITLE
refactor: using multi-stage build to retrieve certificates

### PR DESCRIPTION
**Pull request by hferentschik**
- simplifying Makefile

fixes issue #60

### CODE REVIEW

**Comment by hferentschik** [comment]
@rawlingsj, @jglick - What Docker version are we using under the hood? Seems multi-staged builds are not working in the CI build. 

```
+ make skaffold-build
skaffold build -f skaffold.yaml
time="2019-02-05T08:33:09Z" level=warning msg="config version (skaffold/v1alpha2) out of date: upgrading to latest (skaffold/v1beta3)"
Starting build...
Building [jenkins-x-apps/jx-app-jacoco]...
Sending build context to Docker daemon  525.8kB
Sending build context to Docker daemon  17.79MB
Sending build context to Docker daemon  33.14MB
Step 1/8 : FROM alpine:latest as certs
time="2019-02-05T08:33:11Z" level=fatal msg="build failed: building [jenkins-x-apps/jx-app-jacoco]: build artifact: Error parsing reference: \"alpine:latest as certs\" is not a valid repository/tag: invalid reference format"
Makefile:69: recipe for target 'skaffold-build' failed
make: *** [skaffold-build] Error 1
```

Locally this works fine. 

If multi stage builds are not allowed, can we use Alpine as base image?

**Comment by rawlingsj** [comment]
> What Docker version are we using under the hood? Seems multi-staged builds are not working in the CI build.

We have docker `18.06.1-ce` on the GKE nodes but I just checked and the client we use is `17.12.0` https://github.com/jenkins-x/jenkins-x-serverless/blob/1a2362f/Dockerfile.base#L21 we could try and upgrade but we're currently looking to move away from mounting the docker socket this week and switch to kaniko so maybe use Alpine for now and switch when we get Kaniko sorted?

**Comment by hferentschik** [comment]
> We have docker `18.06.1-ce` on the GKE nodes but I just checked and the client we use is `17.12.0` https://github.com/jenkins-x/jenkins-x-serverless/blob/1a2362f/Dockerfile.base#L21

That explains it.

> we could try and upgrade but we're currently looking to move away from mounting the docker socket this week and switch to kaniko 

Fair enough. No point fiddling around if we (try) moving away from it. Kaniko makes sense anyways.

> so maybe use Alpine for now and switch when we get Kaniko sorted?

Ok. OOI, Kaniko supports multi-stage builds out of the box?

**Comment by hferentschik** [comment]
Ok, pushed an update. Using Alpine directly for now until Kaniko is sorted out.

**Review by daveconde — APPROVED** [review]

**Review by deanesmith — APPROVED** [review]

**Comment by jglick** [comment]
> Kaniko supports multi-stage builds out of the box?

Apparently: https://github.com/GoogleContainerTools/kaniko/pull/141

**Pull request merged**
